name: Release (JAR Package)
on:
   push:
      tags:
      - v*
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            fetch-depth: 0
      -  name: Set up JDK
         uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
            settings-path: ${{ github.workspace }} # location for the settings.xml file
      -  name: Cache SonarCloud packages
         uses: actions/cache@v1
         with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      -  name: Cache Maven packages
         uses: actions/cache@v1
         with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
      -  name: Build and analyze
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: mvn -B package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      -  name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false
      -  name: Upload Release Asset
         id: upload-release-asset
         uses: actions/upload-release-asset@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./target/*.jar